// This file was generated by RedwoodJS
import CancelPageType from '/Users/Chris/dev/rw/payments/sandbox/web/src/pages/CancelPage/CancelPage'
import CustomPaymentFlowPageType from '/Users/Chris/dev/rw/payments/sandbox/web/src/pages/CustomPaymentFlowPage/CustomPaymentFlowPage'
import FatalErrorPageType from '/Users/Chris/dev/rw/payments/sandbox/web/src/pages/FatalErrorPage/FatalErrorPage'
import HomePageType from '/Users/Chris/dev/rw/payments/sandbox/web/src/pages/HomePage/HomePage'
import NotFoundPageType from '/Users/Chris/dev/rw/payments/sandbox/web/src/pages/NotFoundPage/NotFoundPage'
import PaymentIntentGraphqlPageType from '/Users/Chris/dev/rw/payments/sandbox/web/src/pages/PaymentIntentGraphqlPage/PaymentIntentGraphqlPage'
import PrebuiltCheckoutPageType from '/Users/Chris/dev/rw/payments/sandbox/web/src/pages/PrebuiltCheckoutPage/PrebuiltCheckoutPage'
import SuccessPageType from '/Users/Chris/dev/rw/payments/sandbox/web/src/pages/SuccessPage/SuccessPage'

declare global {
  const CancelPage: typeof CancelPageType
  const CustomPaymentFlowPage: typeof CustomPaymentFlowPageType
  const FatalErrorPage: typeof FatalErrorPageType
  const HomePage: typeof HomePageType
  const NotFoundPage: typeof NotFoundPageType
  const PaymentIntentGraphqlPage: typeof PaymentIntentGraphqlPageType
  const PrebuiltCheckoutPage: typeof PrebuiltCheckoutPageType
  const SuccessPage: typeof SuccessPageType
}
